simulation:
  n_cargas: 1

intervals:
  parametro_eps0: 8.8541878128e-12

densidade_carga:
  # tipo: senoide
  # parametros:
  #   amplitude_fator: 7.402203300817018     # A = fator × ε₀  (fator = 3π²/4)
  #   n: 1
  #   m: 1
  #   l: 1

  tipo: gaussiana
  parametros:
    amplitude: 100.0e-10
    largura: 0.15
    centro_x: 0.3
    centro_y: -0.2
    centro_z: 0.4

  # tipo: gaussiana_dupla
  # parametros:
  #   A1: 1.0e-10
  #   A2: -0.8e-10
  #   sigma1: 0.15
  #   sigma2: 0.10
  #   c1: [0.3, -0.2, 0.4]
  #   c2: [-0.4, 0.3, -0.2]

solver:
  N: 20
  dominio:
    xmin: -1.0
    xmax: 1.0
    ymin: -1.0
    ymax: 1.0
    zmin: -1.0
    zmax: 1.0

seed: 42

mlp:
  hidden_dims: [64, 128, 256]       # camadas ocultas
  activation: "relu"                # função de ativação
  batch_size: 128                   # tamanho do batch
  epochs: 500                       # número de épocas
  learning_rate: 0.001              # taxa de aprendizado
  weight_decay: 0.0001              # regularização L2